### ISSUE TITLE
[new submission] resource.images.skinbackgrounds.titanium

### ISSUE THREAD

**Issue by marcelveldt** [xbmc/repo-resources#19]
- Add-on name: Skin Backgrounds Pack - Titanium
- Add-on ID: resource.images.skinbackgrounds.titanium
- Version number: 1.0.0
- Kodi/repository version: Jarvis
- URL: https://github.com/marcelveldt/resource.images.skinbackgrounds.titanium
- Revision/tag: latest
- Branch: master

### Description of changes:
Image resource addon with various high quality backgrounds.

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-resources/blob/master/CONTRIBUTING.md) document

**Comment by ronie** [comment]
would it be possible to use a more generic name instead of the .titan extension?
as mentioned previously, the aim is to provide resource addons that can be used by any skin.
using the name of the skin in the resource addon makes them a bit skin specific.

i realize it's just a cosmetic change, but i'd like to encourage skinners to create generic resource addons, instead of simply moving graphics out of their skin into a resource addon.

(question applies to your other PR's as well)

**Comment by marcelveldt** [comment]
@ronie I've updated all PR's with new names ;-)

**Comment by ronie** [comment]
great, much appreciated!

added, thx!
https://github.com/xbmc/repo-resources/commit/562504f9beb1c24537bcae480b8374b486c2fbc6
